version: '3.4'

volumes:
  datafiles:

services:
  #database:
  #  image: mysql:latest
  #  ports:
  #    - "3306:3306"
  #  volumes: 
  #    - datafiles:/var/lib/mysql
  #    #- ./sql-scripts/setup.sql:/docker-entrypoint-initdb.d/01.sql
  #  environment: 
  #    MYSQL_RANDOM_ROOT_PASSWORD: 1
  #    MYSQL_USER: pumauser
  #    MYSQL_PASSWORD: PumaPrey123!
  #    MYSQL_DATABASE: pumaprey
  #  restart: always   

  gopher.web:
    container_name: app_web
    image: ${DOCKER_REGISTRY-}gopher.web
    #depends_on:
    #  - gopher.api
    build:
      context:  /src/Gopher/ClientApp
      dockerfile: Dockerfile
    volumes: 
      - '/src/Gopher/ClientApp:/usr/share/app'
      - /app/node_modules/
    ports:
      - 4200:4200
    
  #gopher.api:
  #  container_name: api_gateway
  #  image: ${DOCKER_REGISTRY-}gopher.api
  #  ports:
  #    - "80:80"    
  #  build:
  #    context: .
  #    dockerfile: /src/Gopher/Dockerfile           
